Lab1
Katalien/OS_Lab pull request #2
Opened 2023-10-29 16:53 UTC by Katalien

В первом ПР были проблемы с коммитами, так как изначально залила все в ветку main и потом удаляла файлы, чтобы ветка main была пустая. Из-за этого пошли конфликты в ПР. Исправила конфликты в ветках и коммитах.

2023-11-02 16:52 UTC, DariaWelt requested changes
демон падает с сообщением в лог:
ноя 02 19:46:49 daria-0-1 Daemon[57472]: Read config
ноя 02 19:46:49 daria-0-1 Daemon[57472]: Destruct old pid
ноя 02 19:46:49 daria-0-1 Daemon[57472]: Can't check that old pid
ноя 02 19:46:49 daria-0-1 Daemon[57472]: Fork
ноя 02 19:46:49 daria-0-1 Daemon[57473]: Write new pid
ноя 02 19:46:49 daria-0-1 Daemon[57473]: Can't open pid file

2023-11-02 16:52 UTC, DariaWelt commented on LAB1/Daemon.hpp
> +    Daemon() = default;
Конструктор по умолчанию доступен извне класса. Это не синглтон

2023-11-02 16:52 UTC, DariaWelt commented on LAB1/Daemon.hpp
> +    void createDaemon(std::string configPath);
Передается не по ссылке

2023-11-02 16:52 UTC, DariaWelt commented on LAB1/Daemon.hpp
> +    const std::filesystem::path PID_PATH = std::filesystem::path{ "/var/run/daemon.pid" };
можно constexpr

2023-11-02 16:52 UTC, DariaWelt commented on LAB1/folder1/1.txt
> +cjhdhcjhfieje
Удалите из пр тестовые файлы, пожалуйста. Здесь это излишне

2023-11-02 16:52 UTC, DariaWelt commented on LAB1/Daemon
бинарников в пр быть не должно

2023-11-02 16:52 UTC, DariaWelt commented on LAB1/build.sh
> +cp ./build/Daemon .
Daemon не исполняемый файл 
https://beebom.com/how-make-file-executable-linux/

2023-11-04 16:21 UTC, Katalien commented on LAB1/Daemon.hpp
> +    Daemon() = default;
Сделала конструктор приватным. Теперь невозможно напрямую обратиться к конструктору извне класса.

2023-11-04 16:21 UTC, Katalien commented on LAB1/Daemon.hpp
> +    void createDaemon(std::string configPath);
Исправила. Добавила передачу не строки, а абсолютного пути к конфигурационному файлу.

2023-11-04 16:21 UTC, Katalien commented on LAB1/folder1/1.txt
> +cjhdhcjhfieje
Удалила

2023-11-04 16:22 UTC, Katalien commented on LAB1/Daemon
Исправила

2023-11-04 16:22 UTC, Katalien commented on LAB1/build.sh
> +cp ./build/Daemon .
Сделала файл исполняемым

2023-11-04 16:25 UTC, Katalien commented
Пhотестировала демона. Исправила правки выше, а также нашла ошибку и исправила обработчик сигналов. Демон запускается с правами администратора через sudo.

2023-11-08 08:39 UTC, DariaWelt requested changes
```
(base) daria@daria-0-1:~/Downloads/OS_Lab-lab1/LAB1$ sh build.sh
build.sh: 3: [[: not found
[sudo] password for daria: 
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/daria/Downloads/OS_Lab-lab1/LAB1/build
[ 25%] Building CXX object CMakeFiles/Daemon.dir/main.cpp.o
[ 50%] Building CXX object CMakeFiles/Daemon.dir/Daemon.cpp.o
/home/daria/Downloads/OS_Lab-lab1/LAB1/Daemon.cpp: In function ‘void signalHandler(int)’:
/home/daria/Downloads/OS_Lab-lab1/LAB1/Daemon.cpp:15:36: error: ‘void Daemon::stop()’ is private within this context
   15 |         Daemon::getInstance().stop();
      |                                    ^
In file included from /home/daria/Downloads/OS_Lab-lab1/LAB1/Daemon.cpp:8:
/home/daria/Downloads/OS_Lab-lab1/LAB1/Daemon.hpp:58:10: note: declared private here
   58 |     void stop() { isRunning = false; }
      |          ^~~~
make[2]: *** [CMakeFiles/Daemon.dir/build.make:90: CMakeFiles/Daemon.dir/Daemon.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/Daemon.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

2023-11-08 08:39 UTC, DariaWelt commented on LAB1/Daemon.cpp
> +        Daemon::getInstance().stop();
вызываете приватный метод. Подскажите, как компилировали и проверяли программу?

2023-11-08 09:02 UTC, Katalien commented on LAB1/Daemon.cpp
> +        Daemon::getInstance().stop();
Для запуска:
В терминале: sudo ./build.sh
В папке с проектом появляется файл Daemon.
В терминале: sudo ./Daemon ./config.txt

Для проверки:
Запускала программу методом выше.
В терминале: pidof ./Daemon - показывает pid запущенного процесса. Смотрю логи в лог файле: должны быть строки "START RUNNING PROCESS" и "Start create log files".
Для того, чтобы убить процесс: kill или kill -9 . В логах будет запись "process terminated "
Для повторного чтения конфиг файла: kill -s SIGHUP . В логах будет запись "Read config"
Помимо этого проверяю, что демон выполняет все необходимые требования - создает лог файлы для нужных папок.

2023-11-08 09:05 UTC, DariaWelt commented on LAB1/Daemon.cpp
> +        Daemon::getInstance().stop();
то есть утверждаете, что build.sh у Вас компилируется? Проверьте, правда ли локально .stop() приватен.
Ошибка компиляции:
`error: ‘void Daemon::stop()’ is private within this context`

Функция обработки сигналов - внешняя функция, а не метод демона (так и должно быть). Поэтому из этой функции невозможно вызвать приватный метод класса: мы находимся вне класса

2023-11-08 09:09 UTC, Katalien commented on LAB1/Daemon.cpp
> +        Daemon::getInstance().stop();
Я перепроверила. Когда переносила файлы на Windows не добавила все изменения. В моем коде метод stop() публичный. Внесла изменения

2023-11-08 09:33 UTC, DariaWelt requested changes
Исправьте комментарий ниже, чтобы в системе не получалось ситуации, когда запущено два процесса демона и верните файл config.txt. 
В остальном программа рабочая, осталось исправить это

2023-11-08 09:33 UTC, DariaWelt commented on LAB1/Daemon.hpp
> +    void stop() { isRunning = false; }
При получении сигнала на выход демон должен сразу заканчивать работу, у Вас он ждет какое-то время (sleep) и из-за этого в системе существуют два демона. Это нарушение логики.

```
(base) daria@daria-0-1:~/Downloads/OS_Lab-lab1/LAB1$ ./Daemon config.txt 
(base) daria@daria-0-1:~/Downloads/OS_Lab-lab1/LAB1$ pidof Daemon 
144649 144630
(base) daria@daria-0-1:~/Downloads/OS_Lab-lab1/LAB1$ pidof Daemon 
144649 144630
(base) daria@daria-0-1:~/Downloads/OS_Lab-lab1/LAB1$ pidof Daemon 
144649 144630
(base) daria@daria-0-1:~/Downloads/OS_Lab-lab1/LAB1$ pidof Daemon 
144649 144630
(base) daria@daria-0-1:~/Downloads/OS_Lab-lab1/LAB1$ pidof Daemon 
144649 144630
(base) daria@daria-0-1:~/Downloads/OS_Lab-lab1/LAB1$ pidof Daemon 
144649 144630
(base) daria@daria-0-1:~/Downloads/OS_Lab-lab1/LAB1$ cat /var/run/daemon.pid 
(base) daria@daria-0-1:~/Downloads/OS_Lab-lab1/LAB1$ pidof Daemon 
144649
```

2023-11-08 09:39 UTC, Katalien commented on LAB1/Daemon.hpp
> +    void stop() { isRunning = false; }
Можете, пожалуйста, уточнить, что значит вернуть файл config.txt? Вернуть из метода класса?

2023-11-08 10:35 UTC, DariaWelt commented on LAB1/Daemon.hpp
> +    void stop() { isRunning = false; }
добавить config.txt файл в ПР, раньше он был, но вы его удалили вместе с тестовыми файлами вот тут https://github.com/Katalien/OS_Lab/pull/2/commits/35c65a139565a1ee930604f071ab3589d07504d1

2023-11-08 10:35 UTC, DariaWelt commented on LAB1/Daemon.hpp
> +    void stop() { isRunning = false; }
тестовые файлы в ПР не нужны, а пример конфига нужен

2023-11-08 15:20 UTC, Katalien commented
Исправила kill процесса. Сейчас процесс убивается моментально. Добавила пример файла config.txt

2023-11-08 18:04 UTC, DariaWelt approved these changes
Работа зачтена.

2023-11-08 18:04 UTC, merged