Lab2
Katalien/OS_Lab pull request #3
Opened 2023-11-27 11:59 UTC by Katalien

Для запуска программы:
1) Затянуть к себе файлы с кодом
2) В терминале: "chmod +x ./build.sh"
3)  В терминале: "sudo ./build.sh"
4) В терминале: "./host_conn", где <conn> - название соединения (mq, fifo, socket)
В терминале запустится хост и будет выведен pid хоста.
5) Открыть другой терминал: "./client_conn <host_pid>", где conn - название соединения
6) При успешной сборке в терминале будет надпись: "You can start chatting:"
7) В любом из терминалов можно вводить сообщения для отправки в чат

2023-11-30 19:34 UTC, DariaWelt requested changes

2023-11-30 19:34 UTC, DariaWelt commented on Lab2/host/host.cpp
> +  std::future<std::string> future = std::async(getMessage);
Зачем std::async?

2023-11-30 19:34 UTC, DariaWelt commented on Lab2/client/client.cpp
> +  std::thread connectionThread(&Client::ConnectionJob, this);
std многопоточностью пользоваться нельзя, используйте pthread

2023-11-30 19:34 UTC, DariaWelt commented on Lab2/connections/conn_fifo.hpp
> +    std::string GetName(void) { return m_fifoName; }
метод мог бы быть константным

2023-11-30 19:34 UTC, DariaWelt commented on Lab2/connections/conn_fifo.hpp
> +    ~fifo(void);
Не обязательно переопределять дефолтные деструкторы.

2023-12-03 13:03 UTC, Katalien commented on Lab2/connections/conn_fifo.hpp
> +    std::string GetName(void) { return m_fifoName; }
исправила

2023-12-03 13:03 UTC, Katalien commented on Lab2/connections/conn_fifo.hpp
> +    ~fifo(void);
исправила во всех файлах

2023-12-03 13:05 UTC, Katalien commented
Хочу сдать данную реализацию с std::thread и async  на меньшее количество баллов

2023-12-09 12:09 UTC, DariaWelt commented
> Хочу сдать данную реализацию с std::thread и async на меньшее количество баллов

Тогда объясните зачем вам нужен async? И что будет, если его убрать?

2023-12-09 12:10 UTC, DariaWelt reviewed
После ответа на вопрос могу зачесть с пониженным баллом

2023-12-09 12:28 UTC, Katalien commented
Нам нужно взаимодействие двух потоков. Async нужен, чтобы не блокировать основную работу программы и при этом иметь возможность получать сообщения от в терминале

2023-12-09 12:33 UTC, DariaWelt approved these changes

2023-12-09 12:33 UTC, merged